version: '3'
services:
    frontend:
        restart: unless-stopped
        build: .
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            - CERTBOT_EMAIL=jason@jasonwortley.com
